#local 개발용
services:
  db:
    image: postgres:16
    ports:
      - '5432:5432'
    volumes:
      - ./postgresql/mount:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - api-net

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: es
    environment:
      - node.name=single-node
      - cluster.name=ending-credits
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=endingcredits
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - api-net

  # Redis 서비스 추가
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
    command: redis-server --appendonly yes  # 데이터 지속성을 위한 설정
    networks:
      - api-net

networks:
  api-net:
    name: endingcredits-api